# Generated by Django 2.1.3 on 2018-11-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20181130_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('creation_date',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
