# Generated by Django 2.1.3 on 2018-11-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='comment')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comments',
                'verbose_name': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100, verbose_name='Game title')),
            ],
            options={
                'verbose_name_plural': 'games',
                'verbose_name': 'game',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='tag name')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'verbose_name': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_name', to='cms.Game')),
                ('players', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tournaments',
                'verbose_name': 'tournament',
            },
        ),
        migrations.CreateModel(
            name='TournamentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('text', models.TextField(max_length=1000, verbose_name='post')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled time')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='cms.Tournament')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag', to='cms.Tag')),
            ],
            options={
                'verbose_name_plural': 'tournament_posts',
                'verbose_name': 'tournament_post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='tournament_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_post', to='cms.TournamentPost'),
        ),
    ]
