# Generated by Django 2.1.3 on 2018-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpost',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='is_publish'),
        ),
    ]
