# Generated by Django 2.1.3 on 2019-01-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190123_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='event',
        ),
    ]
