# Generated by Django 2.1.3 on 2019-01-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_game_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='matches',
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='event_game', to='cms.Game'),
            preserve_default=False,
        ),
    ]
