# Generated by Django 2.1.3 on 2019-01-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20190124_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_match', to='cms.Event'),
        ),
    ]
